[tools]
rojo = "rojo-rbx/rojo@7.2.1"
wally = "UpliftGames/wally@0.3.1"
stylua = "JohnnyMorganz/stylua@0.14.2"
selene = "Kampfkarren/selene@0.20.0"
rbxcloud = "Sleitnick/rbxcloud@0.3.0"
remodel = "UpliftGames/remodel@0.12.0-uplift.release.12"