[tools]
rojo = { github = "rojo-rbx/rojo", version="7.2.1"}
wally = { github = "UpliftGames/wally", version = "0.3.1"}
stylua = { github = "JohnnyMorganz/stylu", version = "0.14.2"}
selene = { github = "Kampfkarren/selene", version = "0.20.0"}
rbxcloud = { github = "Sleitnick/rbxcloud", version = "0.3.0"}