name: Staging

on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop
  
jobs:

  deploy:
    name: Deploy Staging
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - uses: ok-nick/setup-aftman@v0.3.0
      name: Install Aftman

    - run: rojo build -o game.rbxl
    - run: rbxcloud experience publish -f game.rbxl -p 6213542949 -u 2279328857 -t published -a ${{ secrets.API_KEY}}