name: Staging

on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop
  
jobs:

  deploy:
    name: Deploy Staging
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - uses: Roblox/setup-foreman@v1
      name: Install Foreman
      with:
          version: "^1.0.0"
          token: ${{ secrets.GITHUB_TOKEN }}
    
    - run: remodel run remodel.lua
    
    - run: rojo build -o game.rbxl
    - run: rbxcloud experience publish -f game.rbxl -p 6213542949 -u 2279328857 -t published -a ${{ secrets.ROBLOX_API_KEY }}